SET search_path TO CustomerOrders;


DROP TABLE IF EXISTS departments CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS customers CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS order_items CASCADE;

